baseURL = "https://www.martinkaptein.com/"
languageCode = "en"
# DefaultContentLanguage = "en"

title = "Martin Kaptein"
theme = "casper"

paginate = 6
DisqusShortname = "martinkaptein"
Copyright = "All rights reserved - 2018"
# copyright = "All rights reserved"
pluralizelisttitles = false

canonifyurls = true

[params]
  description = "Welcome to the website of Martin Kaptein. I am a passionate musician and pianist, but also a technology enthusiast and developer offering various IT services. Furthermore, I am really good with languages. Go to the About page for more information."
  
  #metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = "images/martinkaptein-cover-sardegna-large-min.jpg"
  author = "Martin Kaptein"
  authorlocation = "Enschede, The Netherlands"
  authorwebsite = "https://www.martinkaptein.com/"
  authorbio = "musician, developer, polyglot, philosopher"
  #authoravatar = "https://cdn4.iconfinder.com/data/icons/gray-user-management/512/rounded-512.png"
  logo = "images/logo-white-on-black-circle.png"
  googleAnalyticsUserID = "UA-86096566-3"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  #githubName = "martinkaptein"
  twitterName = "MartinKaptein"
  instagramName = "martinkaptein"
  email = "martinkaptein@outlook.com"
  facebookName = "martin.kaptein"
  # linkedinName = ""
  hideHUGOSupport = true
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "martinkaptein"
    
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"















[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

#[[menu.main]]
#identifier = "musician"
#name = "Musician"
#url = "/musician/"
#weight = 6

[[menu.main]]
identifier = "media"
name = "Media"
url = "/media/"
weight = 3

[[menu.main]]
identifier = "music-lessons"
name = "Music lessons"
url = "/music-lessons/"
weight = 4




[[menu.main]]
identifier = "it-services"
name = "IT services"
url = "/it-services/"
weight = 5

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = 2

[[menu.main]]
identifier = "contact"
pre = "<h3>Contact me</h3>"
name = "Contact"
url = "/contact/"
weight = 1







[permalinks]
post = "blog/:slug/"
page = "/:slug/"