baseURL = "https://www.martinkaptein.com/"
languageCode = "en"
title = "Martin Kaptein"


theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "martinkaptein"
googleAnalytics = "UA-86096566-3"
enableRobotsTXT = true

## Site Settings
[params]
    author = "Martin Kaptein"
    #title = "Title"
    description = "musician, developer, polyglot, philosopher"
    authorimage = "/images/martinkaptein-avatar.jpg"
    dateformat = "Jan 1, 2006"
    highlightjs = true
    # highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "martinkaptein"
    instagram = "martinkaptein"
    #xing = "<username>"
    linkedin = "martin-kaptein-a26661159"
    twitter = "MartinKaptein"
    facebook = "martin.kaptein"
    #stackoverflow = "<username>"
    email = "martinkaptein@outlook.com"

## Main Menu
##################################
[[menu.main]]
    name = "Blog"
    weight = 1
    identifier = "blog"
    url = "/blog/"
##################################

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 2
    url = "/about/"
    
    
[[menu.main]]
identifier = "music-lessons"
name = "Music lessons"
url = "/music-lessons/"
weight = 3

[[menu.main]]
identifier = "media"
name = "Media"
url = "/media/"
weight = 4

[[menu.main]]
identifier = "it-services"
name = "IT services"
url = "/it-services/"
weight = 5

[[menu.main]]
identifier = "contact"
#pre = "<h3>Contact me</h3>"
name = "Contact"
url = "/contact/"
weight = 200
    
    
[permalinks]
#blog = "blog/:slug/"
page = "/:slug/"
posts = "blog"